# numpy基础

### 七月在线python数据分析集训营 julyedu.com

褚则伟 zeweichu@gmail.com

## Numpy简介

- Numpy是Python语言的一个library [numpy](http://www.numpy.org/)
- Numpy主要支持矩阵操作和运算
- Numpy非常高效，core代码由C语言写成
- 我们第三课要讲的pandas也是基于Numpy构建的一个library
- 现在比较流行的机器学习框架（例如Tensorflow/PyTorch等等），语法都与Numpy比较接近

## 目录
- 数组简介和数组的构造(ndarray)
- 数组取值和赋值
- 数学运算
- broadcasting广播

python里面调用一个包，用import对吧, 所以我们import `numpy` 包:

如果还没有安装的话，你可以在command line界面使用`pip install numpy`

In [1]:
import numpy as np

## Arrays/数组

### 七月在线python数据分析集训营 julyedu.com

看你数组的维度啦，我自己的话比较简单粗暴，一般直接把1维数组就看做向量/vector，2维数组看做2维矩阵，3维数组看做3维矩阵...

可以调用np.array去从list初始化一个数组:

In [2]:
a = np.array([1, 2, 3])  # 1维数组
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # 重新赋值
print(a)            

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # 2维数组
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)  #可以看形状的（非常常用！！！）                  
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [5]:
print(b.size)

6


In [6]:
print(b.dtype)

int64


查看每个element的大小

In [7]:
print(b.itemsize)

8


有一些内置的创建数组的函数:

In [8]:
a = np.zeros((2,2))  # 创建2x2的全0数组
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [9]:
b = np.ones((1,2))   # 创建1x2的全1数组
print(b)

[[ 1.  1.]]


In [10]:
c = np.full((2,2), 7) # 定值数组
print(c) 

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)        # 对角矩阵（对角元素为1）
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [12]:
e = np.random.random((2,2)) # 2x2的随机数组(矩阵)
print(e)

[[ 0.13734445  0.94347017]
 [ 0.2854123   0.21550377]]


In [13]:
f = np.empty((2,3,2)) # empty是未初始化的数据
print(f)
print(f.shape)

[[[ -1.49166815e-154   2.32035160e+077]
  [  2.96439388e-323   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]

 [[ -1.49166815e-154  -1.49166815e-154]
  [  1.48219694e-323   0.00000000e+000]
  [  0.00000000e+000   8.34402697e-309]]]
(2, 3, 2)


In [14]:
g = np.arange(15) # 用arange可以生成连续的一串元素
print(g)
print(g.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


linspace也是一个很常用的初始化数据的手段，它可以帮我们产生一连串等间距的数组

In [119]:
np.linspace(2.0, 3.0, 5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

## 使用reshape来改变tensor的形状
### 七月在线python数据分析集训营 julyedu.com

numpy可以很容易地把一维数组转成二维数组，三维数组。

In [15]:
import numpy as np

arr = np.arange(8)
print("(4,2):", arr.reshape((4,2)))
print()
print("(2,2,2):", arr.reshape((2,2,2)))

(4,2): [[0 1]
 [2 3]
 [4 5]
 [6 7]]

(2,2,2): [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


直接把shape给重新定义了其实也可以

In [16]:
arr = np.arange(8)
arr.shape = 2,4
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

如果我们在某一个维度上写上-1，numpy会帮我们自动推导出正确的维度

In [17]:
arr = np.arange(15)
print(arr.reshape((5,-1)))
print(arr.reshape((5,-1)).shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(5, 3)


还可以从其他的ndarray中获取shape信息然后reshape

In [18]:
other_arr = np.ones((3,5))
print(other_arr.shape)
print(arr.reshape(other_arr.shape))

(3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


高维数组可以用ravel来拉平

In [19]:
print(arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### 数组的数据类型 dtype

数组可以有不同的数据类型

生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

In [20]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

float64


In [21]:
arr = np.array([1,2,3], dtype=np.int32)
print(arr.dtype)

int32


有时候如果我们需要ndarray是一个特定的数据类型，可以使用astype复制数组并转换数据类型

In [22]:
int_arr = np.array([1,2,3,4,5])
float_arr = int_arr.astype(np.float)
print(int_arr.dtype)
print(float_arr.dtype)

int64
float64


使用astype将float转换为int时小数部分被舍弃

In [23]:
float_arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = float_arr.astype(dtype = np.int)
print(int_arr)

[ 3 -1 -2  0 12 10]


使用astype把字符串转换为数组，如果失败抛出异常。

In [24]:
str_arr = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
float_arr = str_arr.astype(dtype = np.float)
print(float_arr)

[  1.25  -9.6   42.  ]


astype使用其它数组的数据类型作为参数

In [25]:
int_arr = np.arange(10)
float_arr = np.array([.23, 0.270, .357, 0.44, 0.5], dtype = np.float64)
print(int_arr.astype(float_arr.dtype))
print(int_arr[0], int_arr[1])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
0 1


更多的内容可以读读[文档](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Array indexing/数组取值和赋值

### 七月在线python数据分析集训营 julyedu.com

Numpy提供了蛮多种取值的方式的.

可以像list一样切片（多维数组可以从各个维度同时切片）:

In [19]:
import numpy as np

# 创建一个如下格式的3x4数组
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 在两个维度上分别按照[:2]和[1:3]进行切片，取需要的部分
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


虽然，怎么说呢，不建议你这样去赋值，但是你确实可以修改切片出来的对象，然后完成对原数组的赋值.

In [20]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0]改了，很遗憾a[0, 1]也被修改了
print(a[0, 1])

2
77


关于Copy和View的关系
- 简单的数组赋值，切片，包括作为函数的参数传递一个数组--并不会复制出一个新的数组，只是制造了一个新的reference。所以如果我们在新赋值的变量上改变数组的内容，原来的那个数组内容也会发生改变。这一点千万要注意哦！

In [22]:
b = a
b is a

True

- 使用`view`方法，我们可以拿到数组的一部分或者全部，但是在view上面修改内容还是会把原来的数组给更改了

In [21]:
c = a.view()
c is a

False

使用`base`方法可以查看一个数组的owner是谁，也就是说这个数组是由谁制造产生的。

In [26]:
c.base is a

False

其实使用切片方法我们拿到的也是一个view

In [27]:
s = a[:, 2:]
s.base is a

True

所以更改切片上的内容之后，原来数组的内容也被更改了

In [28]:
s[:] = 10
a

array([[ 0.,  0.],
       [ 0.,  0.]])

如果要复制出一个新的数组，我们就需要使用`copy()`这个方法了

In [29]:
d = a.copy()
d is a

False

In [30]:
d.base is a

False

In [31]:
d[0,0] = 9999
a

array([[ 0.,  0.],
       [ 0.,  0.]])

下面我们继续回到数组切片的问题上

创建3x4的2维数组/矩阵

In [32]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


你就放心大胆地去取你想要的数咯:

In [33]:
row_r1 = a[1, :]    # 第2行，但是得到的是1维输出（列向量）
row_r2 = a[1:2, :]  # 1x2的2维输出
row_r3 = a[[1], :]  # 同上
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


试试在第2个维度上切片也一样的:

In [34]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


dots(...)

In [35]:
import numpy as np
c = np.arange(120).reshape(2,3,4,5)
c[1, ..., 3, :]

array([[ 75,  76,  77,  78,  79],
       [ 95,  96,  97,  98,  99],
       [115, 116, 117, 118, 119]])

下面这个高级了，更自由地取值和组合，但是要看清楚一点:

In [36]:
a = np.array([[1,2], [3, 4], [5, 6]])

# 其实意思就是取(0,0),(1,1),(2,0)的元素组起来
print(a[[0, 1, 2], [0, 1, 0]])

# 下面这个比较直白啦
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [37]:
a = np.arange(4*5*6).reshape(4,5,6)
a[np.arange(4), np.arange(4), [1,3,5,2]]

array([  1,  39,  77, 110])

In [38]:
# 再来试试
print(a[[0, 0], [1, 1]])

# 还是一样
print(np.array([a[0, 1], a[0, 1]]))

[[ 6  7  8  9 10 11]
 [ 6  7  8  9 10 11]]
[[ 6  7  8  9 10 11]
 [ 6  7  8  9 10 11]]


再来熟悉一下

先创建一个2维数组

In [39]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


用下标生成一个向量

In [40]:
b = np.array([0, 2, 0, 1])

你能看明白下面做的事情吗？

In [41]:
print(a[np.arange(4), b]) 

[ 1  6  7 11]


既然可以取出来，我们当然也可以对这些元素操作咯

In [42]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### numpy的条件判断

比较fashion的取法之一，用条件判定去取（但是很好用）:

In [43]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # 就是判定一下是否大于2

print(bool_idx)  # 返回一个布尔型的3x2数组

[[False False]
 [ True  True]
 [ True  True]]


用刚才的布尔型数组作为下标就可以去除符合条件的元素啦

In [44]:
print(a[bool_idx])

[3 4 5 6]


其实一句话也可以完成是不是？

In [45]:
print(a[a > 2])

[3 4 5 6]


那个，真的，其实还有很多细节，其他的方式去取值，你可以看看官方文档。

我们一起来来总结一下，看下面切片取值方式（对应颜色是取出来的结果）：

![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

## Array shape manipulation 数组形状

### 七月在线python数据分析集训营 julyedu.com

## 简单数学运算
### 七月在线python数据分析集训营 julyedu.com

下面这些运算是你在科学运算中经常经常会用到的，比如逐个元素的运算如下:

In [46]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

逐元素求和有下面2种方式

In [47]:
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


逐元素作差

In [48]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


逐元素相乘

In [49]:
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


逐元素相除

In [50]:
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


逐元素求平方根！！！

In [52]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


当然还可以逐个元素求平方

In [53]:
print(x**2)

[[  1.   4.]
 [  9.  16.]]


你猜你做科学运算会最常用到的矩阵内元素的运算是什么？对啦，是求和，用 `sum`可以完成:

In [54]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 数组/矩阵中所有元素求和; prints "10"
print(np.sum(x, axis=0))  # 按行去求和; prints "[4 6]"
print(np.sum(x, axis=1))  # 按列去求和; prints "[3 7]"

10
[4 6]
[3 7]


还有一些其他我们可以想到的运算，比如求和，求平均，求cumulative sum，sumulative product用numpy都可以做到

In [55]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))
print(x.cumsum(axis=0))
print(x.cumprod(axis=1))

2.5
[ 2.  3.]
[ 1.5  3.5]
[[1 2]
 [4 6]]
[[ 1  2]
 [ 3 12]]


我想说最基本的运算就是上面这个样子，更多的运算可能得查查[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

其实除掉基本运算，我们经常还需要做一些操作，比如矩阵的变形，转置和重排等等:

一维数组的排序

In [57]:
arr = np.random.randn(8)
print(arr)
arr.sort()
print(arr)

[-0.60377937  0.04950557  0.45932631  0.52234834  1.23693834 -1.47705421
  0.96970704 -0.36210143]
[-1.47705421 -0.60377937 -0.36210143  0.04950557  0.45932631  0.52234834
  0.96970704  1.23693834]


二维数组也可以在某些维度上排序

In [58]:
arr = np.random.randn(5,3)
print(arr)
arr.sort(1)
print(arr)

[[-1.39180276 -0.99435132 -0.67795344]
 [-0.76370286  0.29910856 -0.23683614]
 [-1.01702641 -0.88539474  0.09222203]
 [ 1.33634109 -1.35228067  0.7837372 ]
 [-0.69231019  1.32190951 -1.28639975]]
[[-1.39180276 -0.99435132 -0.67795344]
 [-0.76370286 -0.23683614  0.29910856]
 [-1.01702641 -0.88539474  0.09222203]
 [-1.35228067  0.7837372   1.33634109]
 [-1.28639975 -0.69231019  1.32190951]]


下面我们做一个小案例，找出排序后位置在5%的数字

In [59]:
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05*len(large_arr))])

-1.59317505959


## Broadcasting
### 七月在线python数据分析集训营 julyedu.com

这个没想好哪个中文词最贴切，我们暂且叫它“传播吧”:<br>
作用是什么呢，我们设想一个场景，如果要用小的矩阵去和大的矩阵做一些操作，但是希望小矩阵能循环和大矩阵的那些块做一样的操作，那急需要Broadcasting啦

我们要做一件事情，给x的每一行都逐元素加上一个向量，然后生成y

In [61]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.zeros_like(x)   # 生成一个和x维度一致的空数组/矩阵
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


比较粗暴的方式是，用for循环逐个相加

In [64]:
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i, j] = x[i, j] + v[j]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


这种方法当然可以啦，问题是不高效嘛，如果你的x矩阵行数非常多，那就很慢的咯:

In [65]:
import time

In [79]:
start = time.time()
x = 200 * np.ones((5000, 6000))
v = 300 * np.ones((6000))
y = np.zeros_like(x)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i, j] = x[i, j] + v[j]
print(y)
print("It took {} seconds to finish".format(time.time() - start))

[[ 500.  500.  500. ...,  500.  500.  500.]
 [ 500.  500.  500. ...,  500.  500.  500.]
 [ 500.  500.  500. ...,  500.  500.  500.]
 ..., 
 [ 500.  500.  500. ...,  500.  500.  500.]
 [ 500.  500.  500. ...,  500.  500.  500.]
 [ 500.  500.  500. ...,  500.  500.  500.]]
It took 20.091113090515137 seconds to finish


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

因为broadcasting的存在，你上面的操作可以简单地汇总成一个求和操作

In [80]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [81]:
start = time.time()
x = 200 * np.ones((5000, 6000))
v = 300 * np.array((6000))
y = x + v
print("It took {} seconds to finish".format(time.time() - start))

It took 0.2940390110015869 seconds to finish


当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）
3. 当两个ndarray的维度不完全相同的时候，rank较小的那个ndarray会被自动在前面加上一个一维维度，直到与另一个ndaary rank相同再检查是否匹配

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

我们来理解一下broadcasting的这种用法

先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:

In [82]:
v = np.array([1,2,3])  # v 形状是 (3,)
w = np.array([4,5])    # w 形状是 (2,)

print(np.reshape(v, (3, 1)) * w) # (3, 1), (2,) -> (3, 1), (1, 2) -> (3, 2)

[[ 4  5]
 [ 8 10]
 [12 15]]


那如果要把一个矩阵的每一行都加上一个向量呢

In [85]:
x = np.array([[1,2,3], [4,5,6]]) # (2,3)
v = np.array([1,2,3]) # (3,)
print(x + v) #(2, 3), (3,) -> (2, 3), (1, 3) -> (2, 3)

[[2 4 6]
 [5 7 9]]


In [88]:
x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5])    # w 形状是 (2,)
print(x + w) # (2, 3), (2, ) -> (2, 3), (1, 2) -> not compatible

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [89]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


上面那个操作太复杂了，其实我们可以直接这么做嘛

In [90]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


broadcasting当然可以逐元素运算了

In [91]:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

## 逻辑运算
### 七月在线python数据分析班 2017升级版 julyedu.com

where可以帮我们选择是取第一个ndarray的元素还是第二个的

In [93]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(np.where(cond, x_arr, y_arr))

[ 1.1  2.2  1.3  1.4  2.5]


In [94]:
arr = np.random.randn(4,4)
print(arr)

[[-0.24041214 -1.12466425  1.06992075 -0.23819896]
 [-0.09502431 -0.13692606  0.26887254  1.42644692]
 [ 0.21039999  0.68169083 -1.02253203  0.01228459]
 [ 0.02861363  0.18279051  0.89612027 -0.94647195]]


In [95]:
print(np.where(arr > 0, 2, -2))

[[-2 -2  2 -2]
 [-2 -2  2  2]
 [ 2  2 -2  2]
 [ 2  2  2 -2]]


In [96]:
print(np.where(arr > 0, 2, arr))

[[-0.24041214 -1.12466425  2.         -0.23819896]
 [-0.09502431 -0.13692606  2.          2.        ]
 [ 2.          2.         -1.02253203  2.        ]
 [ 2.          2.          2.         -0.94647195]]


In [97]:
cond_1 = np.array([True, False, True, True, False])
cond_2 = np.array([False, True, False, True, False])
result = np.where(cond_1 & cond_2, 0, \
          np.where(cond_1, 1, np.where(cond_2, 2, 3)))
print(result)

[1 2 1 0 3]


In [98]:
arr = np.random.randn(10)
print(arr)
print((arr > 0).sum())

[-0.03128289  1.4532926   0.7087064  -0.55455257  1.01235441  0.99699586
  0.76325883  0.02630161 -1.78633896 -0.98471716]
6


In [99]:
bools = np.array([False, False, True, False])
print(bools.any()) # 有一个为True则返回True
print(bools.all()) # 有一个为False则返回False

True
False


## 连接两个二维数组
### 七月在线python数据分析集训营 julyedu.com

In [100]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate([arr1, arr2], axis = 0))  # 按行连接
print(np.concatenate([arr1, arr2], axis = 1))  # 按列连接

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


所谓堆叠，参考叠盘子。。。连接的另一种表述
垂直stack与水平stack

In [101]:
print(np.vstack((arr1, arr2))) # 垂直堆叠
print(np.hstack((arr1, arr2))) # 水平堆叠

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


拆分数组, 我们使用[split方法](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.split.html)。

split(array, indices_or_sections, axis=0)

第一个参数array没有什么疑问，第二个参数可以是切断的index，也可以是切分的个数，第三个参数是我们切块的维度

In [105]:
arr = np.random.rand(6,6)
print(arr)

[[ 0.74219077  0.91170515  0.48328427  0.85009211  0.48037243  0.90921461]
 [ 0.94565086  0.8749136   0.53234685  0.22947445  0.99657367  0.43010146]
 [ 0.91132388  0.32654873  0.47721199  0.00500553  0.22614869  0.68597483]
 [ 0.98470157  0.04453905  0.93386678  0.71108011  0.70063362  0.27541218]
 [ 0.26688171  0.1137042   0.70554179  0.88194579  0.92845905  0.66635186]
 [ 0.48884575  0.14494942  0.80834614  0.58472372  0.76405197  0.36709379]]


In [106]:
first, second, third = np.split(arr, [1,3], axis = 0)
print(first)
print()
print(second)
print()
print(third)

[[ 0.74219077  0.91170515  0.48328427  0.85009211  0.48037243  0.90921461]]

[[ 0.94565086  0.8749136   0.53234685  0.22947445  0.99657367  0.43010146]
 [ 0.91132388  0.32654873  0.47721199  0.00500553  0.22614869  0.68597483]]

[[ 0.98470157  0.04453905  0.93386678  0.71108011  0.70063362  0.27541218]
 [ 0.26688171  0.1137042   0.70554179  0.88194579  0.92845905  0.66635186]
 [ 0.48884575  0.14494942  0.80834614  0.58472372  0.76405197  0.36709379]]


In [107]:
first, second, third = np.split(arr, [1, 3], axis = 1)
print(first)
print()
print(second)
print()
print(third)

[[ 0.74219077]
 [ 0.94565086]
 [ 0.91132388]
 [ 0.98470157]
 [ 0.26688171]
 [ 0.48884575]]

[[ 0.91170515  0.48328427]
 [ 0.8749136   0.53234685]
 [ 0.32654873  0.47721199]
 [ 0.04453905  0.93386678]
 [ 0.1137042   0.70554179]
 [ 0.14494942  0.80834614]]

[[ 0.85009211  0.48037243  0.90921461]
 [ 0.22947445  0.99657367  0.43010146]
 [ 0.00500553  0.22614869  0.68597483]
 [ 0.71108011  0.70063362  0.27541218]
 [ 0.88194579  0.92845905  0.66635186]
 [ 0.58472372  0.76405197  0.36709379]]


如果我们想要直接平均切分成三块呢？

In [111]:
blocks = np.split(arr, 3, axis = 1)
print(type(blocks)) # 我们会拿到一个list of ndarray
print(len(blocks))
print(blocks)

<class 'list'>
3
[array([[ 0.74219077,  0.91170515],
       [ 0.94565086,  0.8749136 ],
       [ 0.91132388,  0.32654873],
       [ 0.98470157,  0.04453905],
       [ 0.26688171,  0.1137042 ],
       [ 0.48884575,  0.14494942]]), array([[ 0.48328427,  0.85009211],
       [ 0.53234685,  0.22947445],
       [ 0.47721199,  0.00500553],
       [ 0.93386678,  0.71108011],
       [ 0.70554179,  0.88194579],
       [ 0.80834614,  0.58472372]]), array([[ 0.48037243,  0.90921461],
       [ 0.99657367,  0.43010146],
       [ 0.22614869,  0.68597483],
       [ 0.70063362,  0.27541218],
       [ 0.92845905,  0.66635186],
       [ 0.76405197,  0.36709379]])]


堆叠辅助

In [112]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

r_用于按行堆叠

In [113]:
print(np.r_[arr1, arr2])
print()

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [ 0.36640489 -0.12185101]
 [ 0.09280725 -0.06603233]
 [-0.29566467 -0.71438964]]



c_用于按列堆叠

In [114]:
print(np.c_[np.r_[arr1, arr2], arr])
print()

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [ 0.36640489 -0.12185101  3.        ]
 [ 0.09280725 -0.06603233  4.        ]
 [-0.29566467 -0.71438964  5.        ]]



切片直接转为数组

In [115]:
print(np.c_[1:6, -10:-5])
print()

[[  1 -10]
 [  2  -9]
 [  3  -8]
 [  4  -7]
 [  5  -6]]



使用repeat来重复ndarry中的元素

按元素重复

In [116]:
arr = np.arange(3)
print(arr.repeat(3))
print(arr.repeat([2,3,4]))
print()

[0 0 0 1 1 1 2 2 2]
[0 0 1 1 1 2 2 2 2]



指定axis来重复

In [117]:
arr = np.random.rand(2,2)
print(arr)

[[ 0.81251514  0.1056287 ]
 [ 0.10761409  0.04855416]]


In [118]:
print(arr.repeat(2, axis=0))
print(arr.repeat(2, axis=1))

[[ 0.81251514  0.1056287 ]
 [ 0.81251514  0.1056287 ]
 [ 0.10761409  0.04855416]
 [ 0.10761409  0.04855416]]
[[ 0.81251514  0.81251514  0.1056287   0.1056287 ]
 [ 0.10761409  0.10761409  0.04855416  0.04855416]]


Tile: 参考贴瓷砖
[numpy tile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

In [120]:
print(np.tile(arr, 2))
print(np.tile(arr, (2,3)))

[[ 0.81251514  0.1056287   0.81251514  0.1056287 ]
 [ 0.10761409  0.04855416  0.10761409  0.04855416]]
[[ 0.81251514  0.1056287   0.81251514  0.1056287   0.81251514  0.1056287 ]
 [ 0.10761409  0.04855416  0.10761409  0.04855416  0.10761409  0.04855416]
 [ 0.81251514  0.1056287   0.81251514  0.1056287   0.81251514  0.1056287 ]
 [ 0.10761409  0.04855416  0.10761409  0.04855416  0.10761409  0.04855416]]
