# python与numpy基础

## Numpy

我们要开始接触高效计算库Numpy了，你要是之前在实验室用MATLAB之类的语法，你会发现Numpy和它们长得不要太像，爱MATLAB的同学，参考文档可以看[这里](http://wiki.scipy.org/NumPy_for_Matlab_Users)

Numpy是Python语言的一个扩充

python里面调用一个包，用import对吧, 所以我们import `numpy` 包:

In [1]:
import numpy as np

### Arrays/数组

看你数组的维度啦，我自己的话比较简单粗暴，一般直接把1维数组就看做向量/vector，2维数组看做2维矩阵，3维数组看做3维矩阵...

可以调用np.array去从list初始化一个数组:

In [3]:
a = np.array([1, 2, 3])  # 1维数组
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # 重新赋值
print(a)            

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])   # 2维数组
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.shape)  #可以看形状的（非常常用！！！）                  
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


有一些内置的创建数组的函数:

In [6]:
a = np.zeros((2,2))  # 创建2x2的全0数组
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [9]:
b = np.ones((1,2))   # 创建1x2的全1数组
print(b)

[[ 1.  1.]]


In [10]:
c = np.full((2,2), 7) # 定值数组
print(c) 

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)        # 对角矩阵（对角元素为1）
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [47]:
e = np.random.random((2,2)) # 2x2的随机数组(矩阵)
print(e)

[[ 0.72776966  0.94164821]
 [ 0.04652655  0.2316599 ]]


In [52]:
f = np.empty((2,3,2)) # empty是未初始化的数据，默认为0
print(f)
print(f.shape)

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
(2, 3, 2)


In [56]:
g = np.arange(15) # 用arange可以生成连续的一串元素
print(g)
print(g.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


数组可以有不同的数据类型

生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

In [59]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

float64


In [61]:
arr = np.array([1,2,3], dtype=np.int32)
print(arr.dtype)

int32


使用astype复制数组并转换数据类型

In [65]:
int_arr = np.array([1,2,3,4,5])
float_arr = int_arr.astype(np.float)
print(int_arr.dtype)
print(float_arr.dtype)

int32
float64


使用astype将float转换为int时小数部分被舍弃

In [68]:
float_arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = float_arr.astype(dtype = np.int)
print(int_arr)

[ 3 -1 -2  0 12 10]


使用astype把字符串转换为数组，如果失败抛出异常。

In [70]:
str_arr = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
float_arr = str_arr.astype(dtype = np.float)
print(float_arr)

[  1.25  -9.6   42.  ]


astype使用其它数组的数据类型作为参数

In [71]:
int_arr = np.arange(10)
float_arr = np.array([.23, 0.270, .357, 0.44, 0.5], dtype = np.float64)
print(int_arr.astype(float_arr.dtype))
print(int_arr[0], int_arr[1])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
0 1


### Array indexing/数组取值

Numpy提供了蛮多种取值的方式的.

可以像list一样切片（多维数组可以从各个维度同时切片）:

In [203]:
import numpy as np

# 创建一个如下格式的3x4数组
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 在两个维度上分别按照[:2]和[1:3]进行切片，取需要的部分
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print b

[[2 3]
 [6 7]]


虽然，怎么说呢，不建议你这样去赋值，但是你确实可以修改切片出来的对象，然后完成对原数组的赋值.

In [13]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0]改了，很遗憾a[0, 1]也被修改了
print(a[0, 1])

0.0
0.0


In [14]:
# 创建3x4的2维数组/矩阵
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


你就放心大胆地去取你想要的数咯:

In [15]:
row_r1 = a[1, :]    # 第2行，但是得到的是1维输出（列向量）
row_r2 = a[1:2, :]  # 1x2的2维输出
row_r3 = a[[1], :]  # 同上
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [17]:
# 试试在第2个维度上切片也一样的:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


下面这个高级了，更自由地取值和组合，但是要看清楚一点:

In [18]:
a = np.array([[1,2], [3, 4], [5, 6]])

# 其实意思就是取(0,0),(1,1),(2,0)的元素组起来
print(a[[0, 1, 2], [0, 1, 0]])

# 下面这个比较直白啦
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [19]:
# 再来试试
print(a[[0, 0], [1, 1]])

# 还是一样
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [20]:
# 再来熟悉一下
# 先创建一个2维数组
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# 用下标生成一个向量
b = np.array([0, 2, 0, 1])

# 你能看明白下面做的事情吗？
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [22]:
# 既然可以取出来，我们当然可以对这些元素操作咯
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


比较fashion的取法之一，用条件判定去取（但是很好用）:

In [23]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # 就是判定一下是否大于2

print(bool_idx)  # 返回一个布尔型的3x2数组

[[False False]
 [ True  True]
 [ True  True]]


In [24]:
# 用刚才的布尔型数组作为下标就可以去除符合条件的元素啦
print(a[bool_idx])

# 其实一句话也可以完成是不是？
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


那个，真的，其实还有很多细节，其他的方式去取值，你可以看看官方文档。

我们一起来来总结一下，看下面切片取值方式（对应颜色是取出来的结果）：

![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

### Datatypes

我们可以用dtype来看numpy数组中元素的类型:

In [25]:
x = np.array([1, 2])  # numpy构建数组的时候自己会确定类型
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)# 指定用int64构建

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


更多的内容可以读读[文档](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### 数学运算

下面这些运算才是你在科学运算中经常经常会用到的，比如逐个元素的运算如下:

In [26]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 逐元素求和有下面2种方式
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [27]:
# 逐元素作差
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [28]:
# 逐元素相乘
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [29]:
# 逐元素相除
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [30]:
# 逐元素求平方根！！！
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


那如果我要做矩阵的乘法运算怎么办！！！恩，别着急，照着下面写就可以了:

In [81]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# 求向量内积
print(v.dot(w))
print(np.dot(v, w))

219
219


In [80]:
# 矩阵的乘法
print(x.dot(v))
print(np.dot(x, v))

[14 32]
[14 32]


In [82]:
# 矩阵的乘法
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [84]:
# 利用转置矩阵做dot product
arr = np.random.randn(6,3)
print(np.dot(arr.T, arr))

[[ 6.15893615  0.37567871 -0.87041748]
 [ 0.37567871  5.91307228 -3.8307972 ]
 [-0.87041748 -3.8307972   4.44880351]]


高维的tensor也可以做转置

In [86]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [88]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [89]:
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


你猜你做科学运算会最常用到的矩阵内元素的运算是什么？对啦，是求和，用 `sum`可以完成:

In [99]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 数组/矩阵中所有元素求和; prints "10"
print(np.sum(x, axis=0))  # 按行去求和; prints "[4 6]"
print(np.sum(x, axis=1))  # 按列去求和; prints "[3 7]"

10
[4 6]
[3 7]


还有一些其他我们可以想到的运算，比如求和，求平均，求cumulative sum，sumulative product用numpy都可以做到

In [101]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))
print(x.cumsum(axis=0))
print(x.cumprod(axis=1))

2.5
[ 2.  3.]
[ 1.5  3.5]
[[1 2]
 [4 6]]
[[ 1  2]
 [ 3 12]]


我想说最基本的运算就是上面这个样子，更多的运算可能得查查[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

其实除掉基本运算，我们经常还需要做一些操作，比如矩阵的变形，转置和重排等等:

In [35]:
# 转置和数学公式一直，简单粗暴
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [37]:
# 需要说明一下，1维的vector转置还是自己
v = np.array([1,2,3])
print(v)
print(v.T)

# 2维的就不一样了
w = np.array([[1,2,3]])
print(w)
print(w.T)

[1 2 3]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting

这个没想好哪个中文词最贴切，我们暂且叫它“传播吧”:<br>
作用是什么呢，我们设想一个场景，如果要用小的矩阵去和大的矩阵做一些操作，但是希望小矩阵能循环和大矩阵的那些块做一样的操作，那急需要Broadcasting啦

In [38]:
# 我们要做一件事情，给x的每一行都逐元素加上一个向量，然后生成y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # 生成一个和x维度一致的空数组/矩阵

# 比较粗暴的方式是，用for循环逐个相加
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


这种方法当然可以啦，问题是不高效嘛，如果你的x矩阵行数非常多，那就很慢的咯:<br>
咱们调整一下，先生成好要加的内容

In [39]:
vv = np.tile(v, (4, 1))  # 重复4遍v，叠起来
print(vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [40]:
y = x + vv  # 这样求和大家都能看明白对吧
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [41]:
import numpy as np

# 因为broadcasting的存在，你上面的操作可以简单地汇总成一个求和操作
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

In [42]:
# 我们来理解一下broadcasting的这种用法
v = np.array([1,2,3])  # v 形状是 (3,)
w = np.array([4,5])    # w 形状是 (2,)
# 先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [43]:
# 那如果要把一个矩阵的每一行都加上一个向量呢
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])
# 恩，其实是一样的啦
print(x + v)

[[2 4 6]
 [5 7 9]]


In [44]:
x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5])    # w 形状是 (2,)

# 自己算算看？
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [45]:
# 上面那个操作太复杂了，其实我们可以直接这么做嘛
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [46]:
# broadcasting当然可以逐元素运算了
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

接下来我们来看关于where和一些其他的逻辑运算

In [92]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(np.where(cond, x_arr, y_arr))

[ 1.1  2.2  1.3  1.4  2.5]


In [94]:
arr = np.random.randn(4,4)
print(arr)

[[-1.07862334 -0.65839352 -1.13926498 -0.41236049]
 [-0.01210289  0.66752415 -0.60377733  0.59145772]
 [-0.57474232 -0.72783899 -1.45942297 -0.84187951]
 [-0.3159666   0.04350397 -0.09691279 -1.56976571]]


In [95]:
print(np.where(arr > 0, 2, -2))

[[-2 -2 -2 -2]
 [-2  2 -2  2]
 [-2 -2 -2 -2]
 [-2  2 -2 -2]]


In [97]:
print(np.where(arr > 0, 2, arr))

[[-1.07862334 -0.65839352 -1.13926498 -0.41236049]
 [-0.01210289  2.         -0.60377733  2.        ]
 [-0.57474232 -0.72783899 -1.45942297 -0.84187951]
 [-0.3159666   2.         -0.09691279 -1.56976571]]


In [102]:
cond_1 = np.array([True, False, True, True, False])
cond_2 = np.array([False, True, False, True, False])
result = np.where(cond_1 & cond_2, 0, \
          np.where(cond_1, 1, np.where(cond_2, 2, 3)))
print(result)

[1 2 1 0 3]


In [107]:
arr = np.random.randn(10)
print(arr)
print((arr > 0).sum())

[ 0.27350655 -1.51093462  0.26835915 -0.45991855  1.34450904 -1.86871203
  0.04308971  1.69640444 -0.02191351 -0.43875275]
5


In [109]:
bools = np.array([False, False, True, False])
print(bools.any()) # 有一个为True则返回True
print(bools.all()) # 有一个为False则返回False

True
False


一些更高级的ndarray处理

连接两个二维数组

In [118]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate([arr1, arr2], axis = 0))  # 按行连接
print(np.concatenate([arr1, arr2], axis = 1))  # 按列连接

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


所谓堆叠，参考叠盘子。。。连接的另一种表述
垂直stack与水平stack

In [119]:
print(np.vstack((arr1, arr2))) # 垂直堆叠
print(np.hstack((arr1, arr2))) # 水平堆叠

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


拆分数组

In [122]:
arr = np.random.rand(5,5)
print(arr)

[[ 0.08218151  0.25291976  0.990262    0.74980044  0.92433676]
 [ 0.57215647  0.88759783  0.67939949  0.18618301  0.64810013]
 [ 0.21424794  0.5812622   0.33170632  0.40780156  0.00946797]
 [ 0.46223634  0.53574553  0.25289433  0.33226224  0.26110024]
 [ 0.81823359  0.98863697  0.13713923  0.3520669   0.38301044]]


In [128]:
first, second, third = np.split(arr, [1,3], axis = 0)
print(first)
print()
print(second)
print()
print(third)

[[ 0.08218151  0.25291976  0.990262    0.74980044  0.92433676]]

[[ 0.57215647  0.88759783  0.67939949  0.18618301  0.64810013]
 [ 0.21424794  0.5812622   0.33170632  0.40780156  0.00946797]]

[[ 0.46223634  0.53574553  0.25289433  0.33226224  0.26110024]
 [ 0.81823359  0.98863697  0.13713923  0.3520669   0.38301044]]


In [130]:
first, second, third = np.split(arr, [1, 3], axis = 1)
print(first)
print()
print(second)
print()
print(third)

[[ 0.08218151]
 [ 0.57215647]
 [ 0.21424794]
 [ 0.46223634]
 [ 0.81823359]]

[[ 0.25291976  0.990262  ]
 [ 0.88759783  0.67939949]
 [ 0.5812622   0.33170632]
 [ 0.53574553  0.25289433]
 [ 0.98863697  0.13713923]]

[[ 0.74980044  0.92433676]
 [ 0.18618301  0.64810013]
 [ 0.40780156  0.00946797]
 [ 0.33226224  0.26110024]
 [ 0.3520669   0.38301044]]


堆叠辅助

In [135]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
#r_用于按行堆叠
print(np.r_[arr1, arr2])
print()
#c_用于按列堆叠
print(np.c_[np.r_[arr1, arr2], arr])
print()
#切片直接转为数组
print(np.c_[1:6, -10:-5])
print()

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [ 0.04811148 -1.93674347]
 [ 1.19646481  0.17346639]
 [-1.4388562  -1.41584843]]

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [ 0.04811148 -1.93674347  3.        ]
 [ 1.19646481  0.17346639  4.        ]
 [-1.4388562  -1.41584843  5.        ]]

[[  1 -10]
 [  2  -9]
 [  3  -8]
 [  4  -7]
 [  5  -6]]



使用repeat来重复

更多的numpy细节和用法可以查看一下官网[numpy指南](http://docs.scipy.org/doc/numpy/reference/)